local PLUGIN_NAME = "NPC_Shoot_Enemy_Cover_"
local CONSTANTS = {}

CONSTANTS.PLUGIN_NAME = PLUGIN_NAME

CONSTANTS.NET_WORK_STRINGS = {}
CONSTANTS.NET_WORK_STRINGS.PLAYER_EMIT_SOUND = PLUGIN_NAME .. "PLAYER_EMIT_SOUND"
-- CONSTANTS.NET_WORK_STRINGS.PLAYER_EMIT_SOUND_TIME = PLUGIN_NAME .. "PLAYER_EMIT_SOUND_TIME"
-- CONSTANTS.NET_WORK_STRINGS.PLAYER_EMIT_SOUND_LEVEL = PLUGIN_NAME .. "PLAYER_EMIT_SOUND_LEVEL"
-- CONSTANTS.NET_WORK_STRINGS.PLAYER_EMIT_SOUND_POS = PLUGIN_NAME .. "PLAYER_EMIT_SOUND_POS"

CONSTANTS.NPC_CONFIDENT_TIME = 3
CONSTANTS.SOUND_PROPAGATION = {
    referenceDistance = 1,    -- 参考距离，Source units
    thresholdLevel    = 20,   -- 最小可闻 dB，低于此值直接返回 0
    maxDistance       = 3000, -- 最大听觉半径，防止枪声等过大导致全图听到
}

CONSTANTS.NOT_SHOOT_CONDITIONS = {
    COND.LOW_PRIMARY_AMMO,
    COND.NO_PRIMARY_AMMO,
    COND.NO_SECONDARY_AMMO,
    COND.NO_WEAPON,
    COND.WEAPON_BLOCKED_BY_FRIEND
}

CONSTANTS.SHOOT_AT_ENEMY_CONDITIONS = {
    COND.ENEMY_OCCLUDED,
    COND.WEAPON_SIGHT_OCCLUDED
}
CONSTANTS.NOT_SHOOT_AT_ENEMY_CONDITIONS = {
    COND.LOST_ENEMY,
    COND.LOST_PLAYER,
}

CONSTANTS.SHOOT_AT_HINT_CONDITIONS = {
    SOUND_BULLET_IMPACT = COND.HEAR_BULLET_IMPACT,
    SOUND_COMBAT = COND.HEAR_COMBAT,
    SOUND_DANGER = COND.HEAR_DANGER,
    SOUND_MOVE_AWAY = COND.HEAR_MOVE_AWAY,
    SOUND_PLAYER = COND.HEAR_PLAYER
}

CONSTANTS.STRING_TO_NUMBER = {
    SOUND_BULLET_IMPACT = SOUND_BULLET_IMPACT,
    SOUND_COMBAT = SOUND_COMBAT,
    SOUND_DANGER = SOUND_DANGER,
    SOUND_MOVE_AWAY = SOUND_MOVE_AWAY,
    SOUND_PLAYER = SOUND_PLAYER,
}

return CONSTANTS
