local PLUGIN_NAME = "NPC_Shoot_Enemy_Cover_"
local CONSTANTS = {}

CONSTANTS.PLUGIN_NAME = PLUGIN_NAME

CONSTANTS.NET_WORK_STRINGS = {}
CONSTANTS.NET_WORK_STRINGS.PLAYER_EMIT_SOUND = PLUGIN_NAME .. "PLAYER_EMIT_SOUND"
-- CONSTANTS.NET_WORK_STRINGS.PLAYER_EMIT_SOUND_TIME = PLUGIN_NAME .. "PLAYER_EMIT_SOUND_TIME"
-- CONSTANTS.NET_WORK_STRINGS.PLAYER_EMIT_SOUND_LEVEL = PLUGIN_NAME .. "PLAYER_EMIT_SOUND_LEVEL"
-- CONSTANTS.NET_WORK_STRINGS.PLAYER_EMIT_SOUND_POS = PLUGIN_NAME .. "PLAYER_EMIT_SOUND_POS"

CONSTANTS.NPC_CONFIDENT_TIME = 3
CONSTANTS.SOUND_PROPAGATION = {
    referenceDistance = 1,    -- 参考距离，Source units
    thresholdLevel    = 20,   -- 最小可闻 dB，低于此值直接返回 0
    maxDistance       = 3000, -- 最大听觉半径，防止枪声等过大导致全图听到
}

return CONSTANTS
